version: '3.8'

services:
  app:
    build: .
    container_name: entitlements_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    environment:
      # DATABASE_URL will be loaded from the .env file by the application
      # Ensure your .env file has the correct DATABASE_URL for your remote PostgreSQL
      DATABASE_URL: ${DATABASE_URL}
      # Other environment variables for your app
